# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: db
      DATABASE_USER: db
      DATABASE_PASS: db
      DATABASE_URI: mongodb://database:27017
      PORT: 4000
    volumes:
      - ./src:/app/src
    ports:
      - '4000:4000'
    depends_on:
      - database
    networks:
      - nesjs-network
    command: npm run start:dev

  # start the mongodb service as container
  database:
    image: mongo:6.0.9
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: db
      MONGO_INITDB_ROOT_PASSWORD: db
    networks:
      - nesjs-network

networks:
  nesjs-network:
    name: nesjs-network